// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/escape-string-regexp/escape-string-regexp.d.ts
// Type definitions for escape-string-regexp
// Project: https://github.com/sindresorhus/escape-string-regexp
// Definitions by: kruncher <https://github.com/kruncher/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare module "escape-string-regexp" {

  function escapeStringRegexp(str: string): string;

  export = escapeStringRegexp;

}